### ISSUE TITLE
Øverste ledd: skjul hierarki oppover da det er et meningsløst felt

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1205]

**Comment by runningbones** [comment]
Hva betyr dette? Skal man ikke ha lenger mulighet til å bevege seg oppover i heirerakiet?

**Comment by helemork** [comment]
å gå fra katalog til katalog eller fra natur i norge til katalog er meningsløst :D 
i de øvre nivåene er det mer forvirrende enn hjelpsomt. men spørs om vi rekker å se på det.

**Comment by runningbones** [comment]
Inntil vi får kontroll på hvordan finne fylke/kommune og verneområde uten søk, beholder vi katalogen. Uten katalogen vil vi miste funksjonalitet.

**Comment by helemork** [comment]
Vent litt, sist jeg var inne på katalog var siden tom.
Nå er det innhold der, da er jeg absolutt enig med deg.
Men da bør det inn i hovedmenyen.
