### ISSUE TITLE
[Design] bytt ikoner og cursor på forside - kontinuitet 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1211]

**Comment by bjornreppen** [comment]
Hva betyr denne?

**Comment by helemork** [comment]
grafiske element.
du trenger ikke tenke på ting jeg er satt opp på.

**Comment by bjornreppen** [comment]
Mem kan hende jeg er uenig når kilde er PR-avdelongen.. :-)

**Comment by helemork** [comment]
Det er et ganske ille utgangspunkt at man ikke er enige fra starten. 

De vil jo ta bort hele introboksen jeg laget, da det ikke var planlagt på forhånd. Så at vi ikke snakker med dem før vi lager  ting er ganske dumt.

Hadde vært fint om jeg visste hvem man skal spørre om slikt før jeg lager ting :)
