### ISSUE TITLE
Vis meny, ikke kart i navigering

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1242]
- [x]  Vis meny som automatisk førstevalg når man setter en markør, 
- [x]  Vis menyen når man søker på noe i lista, fremfor kart eller forrige valgte som det er nå.
- [x] Når man går mellom vindustørreler (fra mobil der man har valgt kart) - må vi åpne menyen igjen!

**Comment by bjornreppen** [comment]
Hjelp meg å tenk.. hvordan skal logikken her være?
Menyen skal åpne seg når vinduet resizer seg og bredden blir mindre enn en fast verdi?

Jeg tenkte først at dette ikke var så viktig, men så kom jeg på etterpå at dette kan jo skje også når man roterer en device fra landscape til portrait så problemet er vel høyst relevant.

**Comment by helemork** [comment]
når du oppskalerer vinduet fra mobilstørrelse til desktopstørrelse skal du alltid åpne menyen.
det er ingen tilfeller der den ikke skal vises.
så mao når window size > 768 px, vis uansett.
Så mao: rescale event for alle størrelser over 768px er å åpne menyen.

:)

**Comment by bjornreppen** [comment]
.. der tenkte jeg helt motsatt.. takk!  Dette gir mening.
