### ISSUE TITLE
Oppdater tekst for hva som skjer når folk benytter IE

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1244]
- [x] Skriv ny tekst (Øyvind)
- [x] Fortell Helene hvor ny tekst skal (Bjørn)
- [x] Legg inn ny tekst og fremstill ting pent (Helene)
- [x] Finne ut om vi er pålagt at ting fungerer, oversende til Kommunikasjon

**Comment by runningbones** [comment]
Forslag: 
`Du har forsøkt å åpne NiN-kart i nettleserer Internet Explorer. NiN-kart fungerer på de fleste nettlesere, men ikke Internet Explorer. Under følger en liste over nettlesere vi vet fungerer:

Microsoft Edge: Last ned https://www.microsoft.com/nb-no/windows/microsoft-edge

Firefox:	Last ned https://www.moilla.org/nb-NO/firefox/new/

Google Chrome:	Last ned https://support.google.com/chrome/answer/95346?co=GENIE.Platform%3DDesktop&hl=no


Du kan lese om NiN på https://www.Artsdatabanekn.no/NiN`

**Comment by bjornreppen** [comment]
Filen med browser-sjekk ligger her: https://github.com/Artsdatabanken/nin-kart-frontend/blob/master/src/index.js

Ser at det finnes "ferdige" løsninger, for eksempel http://outdatedbrowser.com/en/how - men det blir kanskje å skyte spurv med kanon?
