### ISSUE TITLE
Gi nye navn til Repo så det er lettere for oss OG andre utenfor å finne ut hva som hører til hva.

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1245]
Jeg har ikke endringsrettighet på navnene på andre prosjekt enn dette.
Foreslår følgende endringer:

kverna: nin-egenskapsbank
adb-data-portal : data.artsdatabanken.no-frontend eller open-data-frontend
open-data <-- står som et tomt repository nå, så det er jo litt snedig..??
nin-data: <--- hva er denne?? er det denne som er nin-open-data-config?

ninMapfileCreator: nin-wms-config
grunnkartdataflyt: nin-kartdataflyt eller nin-kart-dataflyt (spørs hvilken som er korrekt)

- [x] Komme med navneforslag (Helene)
- [x] Utføre endringene (Bjørn)

**Comment by bjornreppen** [comment]
Har nå gjort forsøk på å sette rettigheter på team-nivå istedet for prosjekt.  Si fra hvis det ikke virka?

**Comment by bjornreppen** [comment]
Jeg liker forslagene, synes det gjør det enklere å forstå hva det er snakk om.  Prøver meg på et nytt forslag på to av dem, etter å ha tenkt litt ble jeg bekymret for å kuppe ordet "egenskapsbanken".

* nin-data: nin-egenskapsdata (inneholder alle egenskaper (bare data) om natursystem og landskap)
* kverna: nin-egenskapsdata-lastejobb

kverna leser nin-data (+ mange andre kilder) og produserer 1 json per type med sammenstilte data.

open-data tenkte jeg kunne inneholde de data vi trenger for å bygge data.artsdatabanken.no som vi ikke har plass til andre steder, for eksempel lenker til nettsteder, lisenser, kanskje markdown dokumenter som transformeres til HTML under bygging ol.  Det viser seg at jeg hadde begynt lokalt med et repo, men kom ikke lenger.   Grei plan?  Hva burde man kalt denne?

**Comment by helemork** [comment]
jeg har fremdeles ingen settings-knapp :D

**Comment by bjornreppen** [comment]
Jeg er dum!  Nå er det ok!

**Comment by helemork** [comment]
Jeg tenker vi omnavner open-data når vi vet mer korrekt hva den skal inneholde :)
