### ISSUE TITLE
[ Innhold ][ Ny Funksjon ] Aktive kartlag 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1249]
# Mobilversjonen TO-DO liste

### Knapp/aktivering
- [x] Hente frem igjen den gamle aktiveringsknappen mens man tester
- [x] Lag knappen sånn vi hadde tenkt den skulle være i sidebar
- [x] Få knappen til å virke (zoom til)
- [x] Få knappen til å virke (farge)
### Menyen
- [x] Lag Faneknapp
- [x] Lenk opp faneknapp til underside og pass på at states byttes riktig mellom dem
- [x] Gjenbruk layout-tags fra sidebar, Få inn bolker med ting
- [x] Lag layout for liste-elementene
- [x] Hent inn alle fremmede objektikoner vi trenger
- [x] Hent inn data fra hva som er aktivert <-- gjenbruk gammel kode.
- [x] Basiskart må flyttes inn under innstillinger
- [x] fjerne bakgrunnskart  ikke lov

## BJØRN:
- [x] få vis/skjul funksjon på plass. (Øyet) Altså: må gå an å fjerne kartet man står på også. 
- [x] Må legge til at man kan fjerne dem (x knapp må virke) 

### På plass til første versjon
- [x] skjul/vis-bug
- [x] Kartlag må fungere på desktop
- [x] Skjul farge menyvalg for andre ting enn bakgrunnskart frem til neste versjon
- [x] Desktop: må kunne toggle mellom menyfanene.

### Fanebytte
- [x] Når du trykker på zoom til kart fra kartlag tab, må du bytte fane til kart
- [x] Når du trykker på zoom til kart fra meny, må du bytte fane til kart, her får firefox feilmeldingen: 
- [x] Når du trykker på legg til kart, må du bytte fane til kartlag

**Comment by runningbones** [comment]
![image](https://user-images.githubusercontent.com/31729342/55626027-b7219900-57aa-11e9-8c73-f688aef35088.png)

Tror 'aktive kartlag' kan bør nåes fra hamburgermeny. Aktiverknapp kan flyttes tilbake der den ligger. Når et kartlag aktiveres kan dette markesres på med en boble på hamburderen, og på aktive kartlag inne i hamburgermenyen med det antallet aktive lag brukeren har valgt.

**Comment by helemork** [comment]
Her synes jeg du er inne på noe. La oss tegne litt på det!

**Comment by runningbones** [comment]
Aktive lag: legg til "alt" i gjeldende visning, mulighet for å "skru av" underelement i egen meny

**Comment by runningbones** [comment]
Fjern knapp for rafinering av utvalg

**Comment by runningbones** [comment]
ikke eget søkevindu i aktive lag, bruk samme søkevindu for alle søk

**Comment by helemork** [comment]
![1  meny - zoom knapp og legg til kartlag](https://user-images.githubusercontent.com/17450081/56720063-3834d600-6742-11e9-9abe-8c6d478168b9.png)
![2  kartsiden](https://user-images.githubusercontent.com/17450081/56720064-3834d600-6742-11e9-9df1-214934b157ed.png)
![3  kartlag landingsside](https://user-images.githubusercontent.com/17450081/56720065-3834d600-6742-11e9-8c3f-22f337b13860.png)
![4  alternativ 1 underside-kartlag faner - åpen undermeny](https://user-images.githubusercontent.com/17450081/56720066-3834d600-6742-11e9-8221-311c5d09f277.png)

**Comment by helemork** [comment]
Kommentar fra Slack-diskusjon (forkortet)

### Egne Skjermbilder for innstillinger
* Bjørn: Under settings-menyen blir det for hvert element eks. landskap potensielt mye som kan justeres på..  (type visualisering, farger, filtrering, skalanivå slideren fra landskap + innstillinger relatert til den aktuelle visualiseringen) => så det det kan være fornuftig å tenke egne skjermbilder.. 

  * Helene: og ja, tenkte at å trykke på ting under instillingene tar deg til eget skjermbilde :slightly_smiling_face: men inntil nå er det kunn bakgrunnskart der

### Ekspander på mobil
* Bjørn: noe skeptisk til ekspander (på mobil)  retro?
  * Helene:  Helt enig. Prøvde å tenke noen andre løsninger - har noen bilder av det og, men de ble generelt mindre bra enn dette så da trenger jeg gode innspill fra noen andre.

### Koder 
* Øyvind: Ønsker mulighet for å få koder i tillegg til navn på valgte element. 

### Ikoner
* Øyvind: Vi bør få oss ikoner for LA, NA ++ som bl.a. kan brukes for å indikere hvor de aktive lagene hørere hjemme

### Knappstørrelse
* Bjørn: På-knapp rett ved siden av slette-knapp ikke superoptimalt for oss med tommeltotter eller parkinson 
  * Helene og Øyvind: Helt enige, men hvor skal det da puttes? Vi har ikke plass! Hjelp!

### Samtidig visning
* Bjørn: mobil: Se kart og kartlagstweakemenysamtidig samtidig så man umiddelbart får feedback på hvilken effekt det har i kartet når man gjør en justering?  .. for eks. vertikaldelt skjerm med justerbar splitt?
  * Helene: vi har allerede veldig lite plass bare for å vise menyen, blir sabla lite igjen  om man gjør det. forstår ønsket, men hvordan i praksis?

### Bjørns Crazy Forslag 
* Denne er så absurd at han får legge den inn selv :D

**Comment by helemork** [comment]
## Flytskjema 

Legger ved flytskjema for potensielle referanser hit når man diskuterer.

![Untitled](https://user-images.githubusercontent.com/17450081/56720673-a037ec00-6743-11e9-88ee-35d5aa746a8d.png)

## Forslag basert på flytskjema
![knappetrykk](https://user-images.githubusercontent.com/17450081/56720769-ce1d3080-6743-11e9-9141-2fc0083d76f6.jpg)

**Comment by helemork** [comment]
### Mobilversjonen TO-DO liste

*Knapp/aktivering*
- [ ] Hente frem igjen den gamle aktiveringsknappen mens man tester
- [ ] Lag knappen sånn vi hadde tenkt den skulle være
- [ ] Ta bort det gamle som er igjen nå som jeg gjorde tilgjengelig igjen for å mooche kode

*Menyen *
- [ ] Lag Faneknapp
- [ ] Lenk opp faneknapp til underside og pass på at states byttes riktig mellom dem
- [ ] Gjenbruk layout-tags fra sidebar, Få inn bolker med ting
- [ ] Lag layout for liste-elementene
- [ ] Hent inn alle fremmede objektikoner vi trenger
- [ ] Hent inn data fra hva som er aktivert <-- gjenbruk gammel kode.
- [ ] Få lenket ting riktig
- [ ] Få expand ned til å vise alle barna. ser de er tilgjengelige via foreldren, så da bør vi kunne få tak i dem.
- [ ] få vis/skjul funksjon på plass. Denne var litt buggy før, ettersom hover-funkjsonenn gjorde at den ble vist selv når skjult.
- [ ] Vi skal nå også vise/skjule barn. Så vi må finne ut hvordan å takle det
- [ ] Må legge til at man kan fjerne dem
- [ ] Basiskart må flyttes inn under innstillinger
- [ ] skjul den gamle menyen som gjør rare ting.

**Comment by runningbones** [comment]
@helemork kan se ut som @bjornreppen har huket av sine bidrag i checklist øverst i diskusjon.

**Comment by helemork** [comment]
@runningbones bare meg som hadde glemt å slette den gamle nedersteetter å ha flyttet dem :)

**Comment by helemork** [comment]
# Oppsumering
Etter lite møte med Bjørn i dag kom vi frem til at punkene om barn av og hvordan å takle det taes inn en ny issue som kan få lov  vente litt, og at vi midlertidig lager en enklere variant.

### Problemstillinger:
* Hvordan takle at det er så enormt mange barn i noen tilfeller
* Skal det gå an å endre farge på dem i tillegg til å skru av/på?
* Skru alle av/på?

### Historikk
* Må hente inn historikken først
* Den du er på nå ansees som historikk's øverste ledd, uansett om du legger den til andre steder.
