### ISSUE TITLE
[ Sidestruktur ] Zoom til har feil utsnitt på desktop

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1263]
## På Deskop:
Når du klikker på "Zoom til" knappen, velger den å zoome skjermen din.
Men! Den zoomer med hele det tilgengelige kartvinduet, som vil si at hvis du har menyen åpen på desktop når du zoomer, vil veldig mye av det som zoomes legge seg bak menyen.

### Potensiell løsning?
Her burde den detektert at sidebaren er åpen, og da valgt det resterend utsnittet til å zoome kartet innenfor isteden

## På mobil - Litt viktig!
Når man klikker på "Zoom til"-knappen burde den velge å vise kartet igjen, ikke fortsette å være på nåværende tab. Da ser det ut som om den ikke virker.

**Comment by bjornreppen** [comment]
Hvis vi alltid skal ha sidebar synlig på desktop kan det enkleste være å  justere slik at kartet bare fyller plassen til høyre for sidebar, istedet for hele vinduet også under sidebar?

**Comment by helemork** [comment]
Ja, det kan være en løsning. U fix?

**Comment by helemork** [comment]
Ved nøyere ettertanke:
Ønsker vi å alltid ha sidebaren åpen?

**Comment by helemork** [comment]
Ikke lengre relevant  når #1249 godkjennes, for nå zoomes den til hele skjermen, men menyen kan skjules. mye bedre logikk!
