### ISSUE TITLE
X-Knapp i mobilversjon søkeboks virker ikke

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1266]

**Comment by bjornreppen** [comment]
X-knappen virker..det er bare at knappen forsvinner akkurat når du klikker på den og blir erstattet av forstørrelsesglasset.. fordi søkefeltet mister fokus først :-D

**Comment by bjornreppen** [comment]
Søkefeltet ligger oppå knappen.. derfor virker den ikke.  ;-)

**Comment by helemork** [comment]
what, men, nei, altså
det kan da ikke stemme, den er jo samme sted som søkeikon-knappen var rent kodemessig
