### ISSUE TITLE
Visualisering av landskapstyper

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1270]
Ferdigstille kritiske elementer av visuell framstilling som mangler http://localhost:3001/Natur_i_Norge/Landskap/Typeinndeling og undersider

- [x] Kartfiler for alle landskapstyper https://github.com/Artsdatabanken/nin-kartdataflyt/issues/73
- [x] Kartvisning med bare undertype ved mouseover i undertypeliste meny
- [x] Kartvisning av påvirkede typer ved mouseover i landskapsgradient
- [x] Kartvisning av påvirkede typer ved mouseover i landskapsgradienttrinn

**Comment by helemork** [comment]
Ser ut som denne er ferdig? Isåfall closer jeg den.
