### ISSUE TITLE
[ Data ] Stor grå boks istedet for kart på mange undersider, feilmelding om at noe ikke finnes

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1280]
![image](https://user-images.githubusercontent.com/17450081/55806224-274c5980-5ae0-11e9-83fd-f04e3204a6e7.png)

### DETTE SER VELDIG FEIL UT
forekommer på flere undersider, litt tilfeldig hvor

**Comment by bjornreppen** [comment]
Fant denne bare på landskap.  Lagt inn kartet fra Typeinndeling der.

Relatert til https://github.com/Artsdatabanken/nin-kart-frontend/issues/1300
