### ISSUE TITLE
[ Innlasting ] Mye navigering gir error Unhandled promise rejection e.sources[t] is undefined:

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1302]
Unhandled promise rejection e.sources[t] is undefined: setupRasters/n<@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:149013
setupRasters@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:148994
init@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:141432
init@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:176752
init@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:289049
Zs</t.initStyles@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:297712
updateConfig@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:350587
@blob:https://nin.artsdatabanken.no/9e2e7886-f918-4c4f-abae-94f53119b148:1:28018
tangram.min.js:1127:11
    t tangram.min.js:1127
    qt tangram.min.js:958
    bn tangram.min.js:1123
    <anonymous> tangram.min.js:898
    <anonymous> tangram.min.js:893
    It tangram.min.js:880
    Ft tangram.min.js:884

**Comment by helemork** [comment]
I konsollen får jeg også opp dette - muligens relatert:

Tangram v0.18.0 [warn]: Scene: Could not create data source: undefined 
{…}
​
url: undefined
​
<prototype>: {…}
​​
__defineGetter__: function __defineGetter__()
​​
__defineSetter__: function __defineSetter__()
​​
__lookupGetter__: function __lookupGetter__()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toSource: function toSource()
​​
toString: function toString()
​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
tangram.min.js:1639

**Comment by bjornreppen** [comment]
Sannsynligvis relatert til hacky fjerning av Miljødirektoratet sine "åpne" data.  Flytter  fiksen lenger ut.
