### ISSUE TITLE
[ Universell utforming ] Sidetittel bør inneholde både underside (som nå) og hovedside etterpå

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1305]
* Den skal inneholde en beskrivelse av den spesifikke siden og navnet på nettstedseier.

### Anbefalinger utover kravene i forskriften

Sidetittelen bør innledes med beskrivelse av den spesifikke siden for best mulig brukeropplevelse, ikke med virksomhetens navn. Ettersom det er begrenset plass på nettleserfanen, vil den spesifikke informasjonen bare bli presentert visuelt dersom den kommer først. For brukere med opplesende hjelpemiddel tar det lengre tid å komme til saken når den spesifikke teksten kommer sist.

**Comment by bjornreppen** [comment]
>  ikke med virksomhetens navn. 

denne likte jeg :-)
