### ISSUE TITLE
[Innhold] [Ny Funksjon ] Aktive kartlag fanens interne navigering

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1318]
## Omplassere Tweaks
- [x] Tweaks -> flytte inn i kartlagfanen og få dem til å virke likevel @helemork 
- closes #1324 

## Funksjon (og states) på barn-elementer
- [x] Velg/skjul lag virker ikke for barn av lag @bjornreppen 
- [x] Endre farge virker ikke for barn av lag @helemork
- [x] Endre farge virker ikke for vanlige lag @helemork 

## Øyvinds Ikon i fanevelgeren 
- [ ] Fikse ikon-knappene i menyen så alle har ikon @helemork

## Navigering mellom faner @helemork
- [x] Tweaks sine menyer bør nå ikke flytte på historikken, men toggles internt. @helemork
- [x] Bakgrunnsmeny: Templates
- [x] Bakgrunnsmeny: Fargeinnstillinger
- [x] Visualiseringsvariant -> her må vi tenke ut noe lurt
- [x] gradient
- [x] polygon

**Comment by bjornreppen** [comment]
Planen var å bruke søkedelen av urlen for å peke inn her.  Denne brukes også av klikk i kart.  Hvordan får vi begge deler til å fungere.. sammen ettersom de ligger på to forskjellige tabs?
