### ISSUE TITLE
Rydde opp i slidere

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1324]
- [x] Vanskelig å se håndtak på slidere
- [x] Satt verdi (tall) på slideren vises 2 ganger

**Comment by bjornreppen** [comment]
![image](https://user-images.githubusercontent.com/281359/57606348-ff319980-7568-11e9-986c-b73691f82223.png)

**Comment by runningbones** [comment]
husk måleenhet!
