### ISSUE TITLE
Issues med søkeboks

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1325]
- [x] Mens søkeresultater er åpne fryser alt annet.  Burde forsvinne f.eks. ved klikk utenfor søkeområde
- [x] Mens søkeresultat vises burde forstørrelsesglasset vært en X (relatert til forrige)
- [x] Forstørrelsesglasset flytter på seg ved hover
- [x] Juster plassering av elementer (innholdet i boksen ligger for langt ned)
- [x] Plassere søkefeltet midt i vinduet (nå forskjøvet til høyre)
- [x] Feil mouse cursor ved hover over søkefelt

- issue #1248 Bla i resultater med tastatur
- issue #1342 Går man ut av søkefeltet i mobilvisning blir søkeresultater stående, men søkekriteriet forsvinner
- issue #1342 Hvis man klikker inn i en søkeboks som har et søkekriterie kommer ingen søkeresultater

**Comment by helemork** [comment]
- [x] Aktivere resultater med tastatur er nå mulig
- [ ] Bla i søk via tabulator fungerer, men har ikke lagt til støtte for pil opp/ned.
- [ ] De to nedre punktene til Bjørn er motstridende, vi vil ha enten eller. Enten tømmes søket ved lukking og problemet forsvinner, ellers lar man det stå, men querier på nytt  når man trykker på søk neste gang. Hva vil vi ha?
