### ISSUE TITLE
NiN-kart ligger "nede"

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1327]
**Describe the bug**
Kun infosida som fungerer, all annen navigering fører til "report feedback"

**To Reproduce**
1. Go to https://nin.artsdatabanken.no/
2. Click on 'something"
3. See error

**Comment by bjornreppen** [comment]
Fixed in https://github.com/Artsdatabanken/nin-kart-frontend/pull/1328
