### ISSUE TITLE
LA typer - viser mer enn bare en grunntype i gangen

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1333]
**Describe the bug**
Når man klikker seg inn på en LA-grunntype, viser kartet denne grunntypen. I tillegg virker det som om enkelte andre grunntyper også omfattes av visninga. Det virker som dette er grynntyper som ligger "nær" den valgte typer i kode/GT-nummer.

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Natur_i_Norge/Landskap/Typeinndeling/Innlandslandskap/Innlandsslettelandskap/Innlandsslettelandskap_under_skoggrensen_med_h%C3%B8yt_v%C3%A5tmarkspreg'
2. Click on 'legg til kartlag'
3. CLick on 'noen forskejllige grunntyperobjekt som vises i kartet' 
4. du vil mest sannsylig finn ut at det valgte kartlaget inneholder mer enn den valgte typen

**Expected behavior**
alle objekt i det valgte kartlaget er samme gruynntype

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/57521912-ba67f180-7321-11e9-9fa9-2209becbf0c8.png)
![image](https://user-images.githubusercontent.com/31729342/57521943-cd7ac180-7321-11e9-9e3e-b27126efdd92.png)
![image](https://user-images.githubusercontent.com/31729342/57521967-d8cded00-7321-11e9-9751-d33cd16816ef.png)

**Additional context**
dette er bare et eksempel. Synes å gjelde alle typer (også på et høyere nivå bl.a.https://nin.artsdatabanken.no/Natur_i_Norge/Landskap/Typeinndeling/Innlandslandskap/Innlandsdallandskap)
![image](https://user-images.githubusercontent.com/31729342/57522101-20ed0f80-7322-11e9-8df2-d6bf17cb4816.png)
![image](https://user-images.githubusercontent.com/31729342/57522126-2c403b00-7322-11e9-968c-d6fff00922fb.png)

**Comment by helemork** [comment]
Jeg forstår ikke, kan du tusle hit og peke?

**Comment by runningbones** [comment]
Ser ut til at det meste er fixet, men fortsatt noe gruff på bl.a. XX/Natur_i_Norge/Landskap/Typeinndeling/Kystlandskap/Kystslettelandskap/Skjermet_indre_kystslettelandskap_med_by  (LA-TI-K-S-5)

**Comment by bjornreppen** [comment]
Dersom du testet mot http://nin.artsdatabanken.no kan det se ut som at en forklaring på dette kan være at ny versjon ikke har blitt deployet.   Min lokale master viser riktig, mens den som ligger ute viser feil.

**Comment by bjornreppen** [comment]
Var gjort en antagelse som ikke var fullstendig god, dvs. den fungerte for opprinnelig bruk (gradienter), men ikke på typene. Alle koder med samme prefiks, ble tegnet ut.  Dette var lite gunstig for LA-TI-K-S-5 da f.eks. Grunntype - LA-TI-K-S-57 også har samme prefiks.  Fixed.
