### ISSUE TITLE
[ Data ] Sette område som default fremfor Klassedelt i kartlag-listen, og

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1340]
- [ ]  Sette område som default fremfor Klassedelt i kartlag-listen
- [ ]  G alle store bokstaver. Css tillater kun endring av text-transform på valgt element.
- [ ]  Gi bedre navn, hva i granskauen er klassedelt og områder egentlig betegnelser for i denne sammenhengen?

**Comment by helemork** [comment]
Denne er kanskje dekt nå @bjornreppen  ?

**Comment by bjornreppen** [comment]
Denne issuen tror jeg vi har løst nå?
