### ISSUE TITLE
[ Data ] - Illustrasjonsfoto har blitt erstattet med grafer og figurer

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1344]
Flere av illustrasjons bildene er nå blitt seende ut som grafer fremfor de nydelige naturbildene og landskapsbildene vi hadde før!

Det har blitt nevnt i landskapet at det var litt rart.

**Comment by bjornreppen** [comment]
> Det har blitt nevnt i *landskapet* at det var litt rart.

No pun intended?

**Comment by bjornreppen** [comment]
Enig ja.. Foreslår at vi legger de bildene i en egen "katalog" og så kan vi finne annen plassering for dem, f.eks. interaktive undersider med infographics?`

**Comment by helemork** [comment]
Ja! bare pass på det ikke er disse som dukker opp når man gr inn på ting som illustrasjonfoto så er vi good.
Det virker som om noen her synes dette var meget viktig å fikse med en gang.
