### ISSUE TITLE
la-slider fungerer ikke

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1376]
**Describe the bug**
Slider for oppløsning på LA-kart fungerer ikke

**To Reproduce**
1. Go to 'https://nin.artsdatabanken.no/Natur_i_Norge/Landskap/Typeinndeling'
2. Drag the 'slider'
3. See error

**Expected behavior**
endret oppløsning på kart når slider flyttes

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/59999554-90188c00-9662-11e9-9d17-6a0e335e904f.png)
![image](https://user-images.githubusercontent.com/31729342/59999582-9dce1180-9662-11e9-95e5-7866da27a9d1.png)

**Comment by runningbones** [comment]
Innringer som varslet oss om bug!

**Comment by runningbones** [comment]
Ny kontakt fra bruker som påpeker denne buggen.

**Comment by helemork** [comment]
vi tenker å fjerne den, siden bjørn sa den var vanskelig å fikse logisksett. kan legge midlertidig fix på master.
