### ISSUE TITLE
Lokasjon popup på markør: forslag til ny variant med forbedring

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1382]
![bilde](https://user-images.githubusercontent.com/17450081/60508769-aad6aa80-9ccb-11e9-8321-11bbb1687c37.png)

Figuren viser foreslått flystruktur av Lokasjon

### To Do

DEL A
- [x] Lage markørboksen 
- [x] Fylle markørboksen med innhold
- [x] @bjornreppen returnere søkresultat for alt på infosiden, nå må den inneholde alt som skal vises
- [x] legg til at markøren gir en infoboks man klikker på for å komme seg dit, fremfor å automatisk sende til siden. En fin mellom-info-box. Da kan man også beholde/fjerne markøer etter ønske.
- [x] Lag badges for enkle ting fremfor gradienter

**Comment by bjornreppen** [comment]
Søk med radius (forbedring på sikt):
```
https://vector.artsdatabanken.no/ogapi/radius/8.173828125000002/60.780618803458935/10

https://vector.artsdatabanken.no/ogapi/radius/{longitude}/{latitude}/{radius i meter}
```

**Comment by helemork** [comment]
@bjornreppen jeg tror vi bør tenke litt mer på hvordan vi gjennomfører del B av denne. er ikke helt enig med skissen ovenfor lengre. Den tar utgangspunkt i at boundingbox'en er basert på zoomnivå, men jeg ser litt for meg at de ønsker å stille inn uavhengig av det. La oss tenke det gjennom litt før vi begynner.

**Comment by helemork** [comment]
Her er noen tidligere mockups vi hadde for å se på hvordan å vise stedssiden for sider med variert oppløsning på søket. Siden for fylker og kommuner populeres med innhold. Stedsiden lenkes opp ordentlig med seg selv i lenken og derav bedre kartbladutvalg. Ikke sikker på at jeg er enig med disse lengre, men kan være greit å referere til senere.
 
Legger dem ved da @runningbones ikke hadde sett dem. 

![MOCUKP- STED](https://user-images.githubusercontent.com/17450081/63861584-76215f80-c9ab-11e9-90d6-8837eff0c21d.png)
![MOCUKP  kommune](https://user-images.githubusercontent.com/17450081/63861585-76215f80-c9ab-11e9-8b12-00a75860ef06.png)
![MOCUKP- STED - 2](https://user-images.githubusercontent.com/17450081/63861587-76215f80-c9ab-11e9-87c5-918aa8e4797f.png)

**Comment by helemork** [comment]
Lukker denne og oppretter Bounding Box søk issue: #1491 for å holde det litt ryddigere.
