### ISSUE TITLE
Filter slider hopper til 0

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1383]
- Legg til bioklimatisk seksjon
- Dra min slider til minimum

![image](https://user-images.githubusercontent.com/281359/60812475-dce78100-a191-11e9-84fd-4be37364237e.png)

- Dra så max slider til minimum

![image](https://user-images.githubusercontent.com/281359/60812581-21731c80-a192-11e9-8e38-1672d3a35242.png)

- Dra max slider oppover igjen

Min slider hopper til midt på (0.0)

![image](https://user-images.githubusercontent.com/281359/60812550-0f917980-a192-11e9-94d7-925e0f431587.png)

**Comment by helemork** [comment]
duplicte of #1433
