### ISSUE TITLE
Samsvarende data  i Lokasjons-API (Boring) i forhold til når man lagrer og endrer ting

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1394]
DETTE ER DET VIKTIGSTE AV ALT.
- feil data på kommune, fylke, sted (hentes fra gammelt api)
- feil innhold basert på koordinat, samsvarer ikke med opptegnede landskapstyper i området.
Etter det:
- [x] Få ut mer info på underpunktene (barn av nåværende element) (beskrivelse) (vent med til neste versjon)
- [x] Få ut mer info på stedpunktene (boring trenger bilder, tekst, omstrukturering av api for å lettere få tak i ting) se notat i bok

![bilde](https://user-images.githubusercontent.com/17450081/62468296-03e7a180-b796-11e9-99f7-d66e48ffdc73.png)

**Comment by bjornreppen** [comment]
Fikset i https://github.com/Artsdatabanken/punkt-oppslag-api/commit/78f5d56a46bcb9f11e45753c15bd90975d2f6a28

**Comment by helemork** [comment]
Nope, feil data ennå.
Det stemmer ikke med opptegnede farger i kartene. :)

**Comment by helemork** [comment]
![bilde](https://user-images.githubusercontent.com/17450081/62925401-8f72bb00-bdb2-11e9-810e-10f1706558dd.png)


Etter litt testing kom vi frem til at når man redigerer barna til et element, blir ting feil. Det er ikke initiellt feil.

**Comment by helemork** [comment]
Lukker denne da vi antar dataene vi nå har er korrekte, og at feilen er den andre issuen som ble opprettet.
