### ISSUE TITLE
Åpent fjordlandskap inneholder Nedskåret fjordlandskap

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1401]
![image](https://user-images.githubusercontent.com/281359/62875043-92be6600-bd22-11e9-9545-1d7425b64a01.png)

**Comment by helemork** [comment]
![bilde](https://user-images.githubusercontent.com/17450081/62925401-8f72bb00-bdb2-11e9-810e-10f1706558dd.png)


## Etter Testing har jeg kommet frem til følgende:

Sett at vi har dette oppsettet:
Nåværende kartlag: A
Mine kartlag: B og C
Alle har étt underpunkt.

1) Endring i A påvirker ikke B eller C
2) Endring i B påvirker B og A
3) Endring i C påvirker C og A

B og C påvirker aldri hverandre.

Sett at B har flere underelementer:
1) Når man redigerer B, gir man underelementene til A, så de dupliseres.
2) Endring i A og B vil da begge gi samme resultat for både A og B
3) Endring i C påvirker ikke lengre A.


VIDERE:
- Det virker som et kriterie for at noe skal endres er ulikt antall barn.
- Så lenge denne endres dumpes alt over på A.
