### ISSUE TITLE
LA_TI: Legg inn overskrift for KLG-trinn som definerer typen

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1402]
- quickfix

**Comment by helemork** [comment]
Antar dette er det punktet som jeg hadde skrevet opp som at alle gradienter og miljøvariabler mangler overskrift?
Nå er de automatisk uthentet sånn at det ikke er en overskrift tilgjengelig. Vi har ingen informasjon for landskapsgradienter for eksempel. Teksten på artsdatabanken sin side er ikke spesielt hjelpsom, så tror vi bør skrive vår egen som er mer rettet mot målgruppen.
