### ISSUE TITLE
2. "Burde ikke meny skifte navn til navigering?"

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1408]
edit from @runningbones: Enig i at "meny" er noe abstrakt, men ordet "navigereing" i en kartløsning mener jeg bør forbeholdes den geografiske navigeringa (og ikke inkludere navigering mellom ulike datasett/nivå/etc)

edit from @helemork: Skal da sidebarens tittel endres til Meny også? Vi se litt snedig ut, men greit for meg

**Comment by bjornreppen** [comment]
Jeg tenker man bør forsøke å beskrive hva innholdet er istedet for å hva man kan gjøre der.

**Comment by helemork** [comment]
Betyr det at du vil ha meny? eller navigering?

**Comment by helemork** [comment]
@smistad Burde det hete navigering eller meny?

**Comment by smistad** [comment]
Syns navigering er bedre enn meny, men kanskje ikke helt optimalt det heller.
Mulig det fins en bedre tittel: "Velg nivå", "Nivåvelger", "Bla gjennom"...
