### ISSUE TITLE
administrative områder: forklarende tekst

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1415]
legg inn tekst som kan brukses på adminitrativ grense, herunder hva underelementer inneholder. nb! nevn spesifikt hvor fylke/kommune ligger.

Tekster finnes her: https://www.kartverket.no/globalassets/standard/sosi-standarden-del-1-og-2/produktspesifikasjoner---sosi-del-3/produktspesifikasjon_adm_maritim_versjon_2012-1.pdf
(vedlegg 1, side 53++)

**Comment by helemork** [comment]
Midlertidig mens vi venter på full forklaring har jeg bare dumpet inn føllgende teskst: Norge er blant annet bygget opp av det vi kjenner som fastlandet med fylker og kommuner, som er en betydelig del av vårt territorialområde. Men Norge inneholder også flere øyer og øygrupper, og havområder som omtales som vår kontinentalsokkel."

**Comment by bjornreppen** [comment]
Har også oppdatert typer: https://github.com/Artsdatabanken/maritime-grenser/commit/b958aeab3131a465f7a087a18699b7f60bf036d2#diff-a791ace36dc07dca643a634f9ddaeeac

Mon tro hvorfor det ikke finnes lenke til dokumentet på GeoNorge..

**Comment by helemork** [comment]
P.S. @bjornreppen 
Tove sa vi har hentet ut brødtekst, ikke ingress på blterrenguro og de der. Ingressen er ikke bra den heller, men en smule bedre (og kortere, som jo er nice)

**Comment by helemork** [comment]
Der vi ikke har, populer fra wikipedia

**Comment by bjornreppen** [comment]
Rester ryddes opp i https://github.com/Artsdatabanken/nin-kart-frontend/issues/1510
