### ISSUE TITLE
Bug: Rasterfeil i kart

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1423]
- [x] [Brukertestresultat] Når man går inn på by fra arealbruksintensitet, er det ikke raster, og den laster inn feil. Trondheim er f.eks borte.

- [x] [Brukertestresultat] Gradientene har rasterfeil - mesh bugs

- [x] [Brukertestresultat] gradient kystnær ikke virk

**Comment by bjornreppen** [comment]
De gamle tunge vektoriserte kart er nå borte.   Alle gradienter er nå rasterkart.  

NB: Våtmarkspreg og Relieff gjenstår.
NB2: Inntil overgang fra webmercator til UTM ser ikke kartene så riktige ut som de burde på detaljnivå (behov for mange flere zoomnivå for å få de transformerte 100x100m firkantene til å se riktige ut.

**Comment by bjornreppen** [comment]
Relatert til #1451
