### ISSUE TITLE
Grafikk: Bruk fylkesvåpen på steder fremfor tilfeldige bilder 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1426]
[Brukertestresultat] heller bruke fylkesvåpen enn "de bildene der som ikke er representative for plassen"

**Comment by helemork** [comment]
Denne er bittelitt mer tungvindt enn det ser ut som.

Litt bakgrunnsinfo
* Når man laster opp et bakgrunnsbilde inline (i react) ser det ofte ut som om den også overkjører den verdien som er satt på backgroundSize. Det er derfor jeg aktivt setter den i koden selv om den har en default KartlagBarnElement,js linke 51.
* I et css-hierarki vil cssklasse i en ekstern fil ha lavest rang. Mens det som skrives inline har høyere rang.
* Det vi ønsker er å endre hvoran koden fremstilles i tilfellet som er relevant for oss.
* Komponenten KartlagBarnElement bruker alle steder vi lager underelement, så det er veldig viktig å ikke endre css eller slikt utenfra, kun innenfra via en sjekk.

Så: To-DO
* Lag en sjekk for om KartlagBarnElement sin variabel "url" inneholder substrengen "Administrativ_grense/"  (Tips: det står hvordan man gjør det her: https://stackoverflow.com/questions/1789945/how-to-check-whether-a-string-contains-a-substring-in-javascript )
* Inne i denne, sett new_url til det den skal være for fylker, kommuner og andre adminsiistrative grenser. 
* Vi vil også bytte ut der det står "backgroundSize: "cover"," med backgroundSize: "contain", men kun hvis det er fylke. Så: lag en ny variabel i tillegg til new_url som står som "cover", og endre denne inne i if-kondisjonen din til contain :)
* Bruk denne i steden for "cover" på linje 51.

Ta-Da
Bruk denne variabelen direkte i steden for "cover". Så: la

**Comment by svetlnaumova** [comment]
![Larvik](https://user-images.githubusercontent.com/43623201/64688699-33708480-d48d-11e9-9154-173975c3d638.jpg)

**Comment by helemork** [comment]
Har du lyst å få den enda finere med litt css?
I stedet for å bruke contain, kan du sette background-size til 90% og background-position til senter
Burde gi litt luft rundt bildene.
