### ISSUE TITLE
Navigering: Skille kart og info i url.

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1435]
- Kan via tilbakoepilen bytte mellom dem
- Kan dyttes inn som ? så man slipper at den faktisk er i historikk, men at den er det likevel
- Vil hjelpe mot url-visjonene i ØGK
- Tukler ikke med ting ved refresh

**Comment by helemork** [comment]
jeg jobber med saken, trenger ikke close denn ennå 😄

**Comment by helemork** [comment]
@smistad du snakket om to bugs du så på mobil:
1. noe ble funky når man brukte fullskjermmodus
2. ... hva var denne? tror det var relatert til å bytte fane, en plass noe ikke ble oppdatert, men hvor?

**Comment by smistad** [comment]
Velg kart -> fullskjerm modus -> og så trykk et sted på kartet -> gå til informasjon om dette punktet

Da forsvinner fanene i bunnen på min mobil :)

**Comment by helemork** [comment]
Ja, det var punkt 1, den merger jeg inn nå. men punkt 2? tror det var noe mer du sa var feil?

**Comment by helemork** [comment]
Da sier jeg den lukkes i  #1555. 
Var en chrome-bug.
