### ISSUE TITLE
Natursystem: "Nåværende kartlag" skjules av melding om manglende data

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1454]
**Describe the bug**
Natursystem: "Nåværende kartlag" skjules av melding om manglende data. 

**To Reproduce**
1. Go to 'Gjelder bl.a. https://nin.artsdatabanken.no/Natur_i_Norge/Natursystem/Beskrivelsessystem/Regional_naturvariasjon/Bioklimatisk_sone 
2. Gå til "kart"
3. se venstremeny
4. nåværende kartlag (herunder legende for det aktuelle alget, og muligheten for å legge til mine kartlag er borte/skjules for bruker

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/63996945-62860e00-cafd-11e9-9752-73acd8010b90.png)

**Comment by helemork** [comment]
Den skjules ikke av boksen, jeg aktivt fjerner den :D
Hadde glemt at KLG'ene er tilgjengelige. 
Skal fikse ASAP
