### ISSUE TITLE
[Dokumenasjon] Lag forklaring på hvor ting er og hvordan de oppdateres

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1467]
@bjornreppen  skriv detaljert opppkoblingsoversikt til H så hun selv kan laste opp bilder og endre api ting selv. Må ta med alt, og virke på windows. Test først.

**Comment by bjornreppen** [comment]
Oppskrift for Windows:
- Installer WinSCP fra https://winscp.net/eng/index.php
- Koble til hydra

Aktuelle kataloger:

/home/grunnkart/tilesdata: alle filer tilgjengelig på https://data.test.artsdatabanken.no (kart, metadata, bilder)
/home/grunnkart/statics: Bundle med html og javascriptkoden for frontend.  Eksponert på https://nin.test.artsdatabanken.no

**Comment by helemork** [comment]
Flyttet denne der den bør bo: https://github.com/Artsdatabanken/nin-kart-frontend/wiki/Hvordan-oppdatere-eksterne-api%3F
