### ISSUE TITLE
Legg inn datasett for ØG-forvaltningsportal

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1483]
fra adb: RL-arter og FA
Fra Mdir: Arter av nasjonal forvaltingsinteresse
Ldir/NIBIO; Skoglevende arter

Lenker til tjenester: Asignee: Øyvind

**Comment by runningbones** [comment]
Dataeier | Tema | Datasett | Lenke
-- | -- | -- | --
Kartverket | Administrative inndelinger | Kommuner | https://kartkatalog.geonorge.no/tema/administrative-inndelinger/3?text=&Facets%5B0%5D.name=organization&Facets%5B0%5D.value=Kartverket
Kartverket | Administrative inndelinger | Fylker | https://kartkatalog.geonorge.no/tema/administrative-inndelinger/3?text=&Facets%5B0%5D.name=organization&Facets%5B0%5D.value=Kartverket
Kartverket | Administrative inndelinger | Maritime grenser | https://kartkatalog.geonorge.no/tema/administrative-inndelinger/3?text=&Facets%5B0%5D.name=organization&Facets%5B0%5D.value=Kartverket
NIBIO | Skog | Miljøregistreringer i skog | https://wms.nibio.no/cgi-bin/skogbruksplan?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
NIBIO | Arealressurs | Arealressurskart - FKB-AR5 | https://wms.nibio.no/cgi-bin/ar5?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
Miljødirektoratet | Naturvern | Naturvernområder | https://kart.miljodirektoratet.no/arcgis/services/vern/mapserver/WMSServer?service=wms&request=getcapabilities
Miljødirektoratet | Naturtyper | Naturtyper -  NiN | https://kart.miljodirektoratet.no/arcgis/services/naturtyper_nin/MapServer/WMSServer?service=wms&version=1.1.1&request=getcapabilities
Miljødirektoratet | Naturtyper | Naturtyper  - DN-håndbok 13 | https://kart.miljodirektoratet.no/arcgis/services/naturtyper_hb13/mapserver/WMSServer?request=GetCapabilities&service=WMS
Miljødirektoratet | Naturtyper | Naturtyper - marine (DN håndbok 19) | https://kart.miljodirektoratet.no/arcgis/services/naturtyper_marine_hb19/MapServer/WMSServer?service=wms&version=1.1.1&request=getcapabilities
Miljødirektoratet | Naturtyper | Naturtyper - utvalgte | https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte/mapserver/WMSServer?service=wms&request=getcapabilities
Miljødirektoratet | Arter | Arter av nasjonal forvaltningsinteresse | https://kart.miljodirektoratet.no/arcgis/services/artnasjonal/mapserver/WMSServer?service=wms&version=1.1.1&request=getcapabilities
ADB | Arter | Rødlista Arter | https://kart.artsdatabanken.no/WMS/artskart.aspx?request=GetCapabilities&service=WMS
ADB | Arter | Fremmedarter | https://kart.artsdatabanken.no/WMS/artskartfa.aspx?request=GetCapabilities&service=WMS
ADB | Landskap | Landskap |  
NVE | Ferskvann | Innsjødatabase | https://gis3.nve.no/map/services/Innsjodatabase1/MapServer/WmsServer?request=GetCapabilities&service=WMS
NVE | Ferskvann | Elvenett Elvis | https://gis3.nve.no/map/services/Elvenett1/MapServer/WmsServer?request=GetCapabilities&service=WMS
NVE | Ferskvann | Verneplan for vassdrag | https://gis3.nve.no/map/services/VerneplanforVassdrag/MapServer/WmsServer?request=GetCapabilities&service=WMS

**Comment by bjornreppen** [comment]
Repo for kildedata https://github.com/Artsdatabanken/forvaltningsportal-datasett-ubehandlet

**Comment by bjornreppen** [comment]
Følgende tjenester er ikke satt opp med CORS og kan derfor ikke benyttes rett fra en klient på et domene utenfor leverandøren sitt av en moderne browser:

  https://kartkatalog.geonorge.no/tema/administrative-inndelinger/3?text=&Facets%5B0%5D.name=organization&Facets%5B0%5D.value=Kartverket
  https://kartkatalog.geonorge.no/tema/administrative-inndelinger/3?text=&Facets%5B0%5D.name=organization&Facets%5B0%5D.value=Kartverket
  https://kartkatalog.geonorge.no/tema/administrative-inndelinger/3?text=&Facets%5B0%5D.name=organization&Facets%5B0%5D.value=Kartverket
  https://kart.miljodirektoratet.no/arcgis/services/vern/mapserver/WMSServer?service=wms&request=getcapabilities
  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_nin/MapServer/WMSServer?service=wms&version=1.1.1&request=getcapabilities
  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_hb13/mapserver/WMSServer?request=GetCapabilities&service=WMS
  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_marine_hb19/MapServer/WMSServer?service=wms&version=1.1.1&request=getcapabilities
  https://kart.miljodirektoratet.no/arcgis/services/naturtyper_utvalgte/mapserver/WMSServer?service=wms&request=getcapabilities
  https://kart.miljodirektoratet.no/arcgis/services/artnasjonal/mapserver/WMSServer?service=wms&version=1.1.1&request=getcapabilities

Følgende tjenester er OK:

  https://wms.nibio.no/cgi-bin/skogbruksplan?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
  https://wms.nibio.no/cgi-bin/ar5?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
  https://kart.artsdatabanken.no/WMS/artskart.aspx?request=GetCapabilities&service=WMS
  https://kart.artsdatabanken.no/WMS/artskartfa.aspx?request=GetCapabilities&service=WMS

**Comment by bjornreppen** [comment]
Blokkert av #1493

**Comment by bjornreppen** [comment]
Lukker denne, da ting er klargjort.  CORS-problematikk håndteres videre i https://github.com/Artsdatabanken/nin-kart-frontend/issues/1493
