### ISSUE TITLE
Legg til kartlag til mockup visning test

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/nin-kart-frontend#1484]
#1483

**Comment by bjornreppen** [comment]
Repo for kildedata: https://github.com/Artsdatabanken/forvaltningsportal-datasett-ubehandlet

**Comment by bjornreppen** [comment]
Blokkert av #1483

**Comment by bjornreppen** [comment]
Datagrunnlag er nå klare i https://data.artsdatabanken.no/forvaltningsportal.json

Gjenstår frontend.
