### ISSUE TITLE
Integrer wms-tjenester i aktive kartlag

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1495]
Sørg for at funksjonaliteten vår også fungerer på WMS-kart:

- Av/På
- Alpha blend
- Stokking av lag
- Fjerne/Legge til

Fungerende kodeeksempel:  https://github.com/Artsdatabanken/nin-kart-frontend/commit/21f4d0e50237712b3434cff333f7e7d9c0d84dea

![image](https://user-images.githubusercontent.com/281359/64733759-9f7ed700-d4e5-11e9-80b5-60845cec4679.png)

**Comment by helemork** [comment]
Cannot GET /forvaltningsportal.json

**Comment by bjornreppen** [comment]
Fixed by @myrdrahl

**Comment by bjornreppen** [comment]
Fixed in ae6bc005eef8ac84ef2f77b1834c34d2f9c9e110
