### ISSUE TITLE
Tillat zoom 200%

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1505]
### Make sure that the interface can be zoomed at least 200 percent
At the moment you have locked the interface from zooming with the code:
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0">
You have to, at least, let the user zoom the interface 200 percent.
Note that many desktop browsers ignore this code, but some browsers on mobile devices listen to this and then the interface is locked for zooming.
### Suggested solution
Let users zoom the interface, at least 200 percent, but we recommend at least 400 percent. The interface might be more difficult to use but it should be possible to use even when zoomed.
### Priority (1-4)
Medium (3) 
### WCAG relation
1.4.4 Resize text (level A)

[H: hva i granskaue, @bjornreppen, hvorfor er dete deaktivert?]

**Comment by bjornreppen** [comment]
> [H: hva i granskaue, @bjornreppen, hvorfor er dete deaktivert?]

Fordi jeg ønsket at den skulle oppføre seg som en app, ikke som en webside.  Dvs. at man istedet for å zoome inn på et område i appen, heller f.eks. endrer font-størrelse hvis man sliter med å se.  

Hovedutfordringen var nok (i et fullskjermskart) at hvis pinch-to-zoom skal zoome alt.. hvordan zoomer man da i kartet?

**Comment by bjornreppen** [comment]
Fixed.
