### ISSUE TITLE
[Universell utforming ] Marker språk som støttes i headerens metadata

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/nin-kart-frontend#1506]
Her er react meget teit og nekter oss tilgang til metadataen vår. What to do,?

Set the default language correctly
The default language of the content is set to English:
 
This should be set to reflect the main language of the content.
At the moment some screen readers use an English voice to read the text because of this. This makes the text hard to read.
Suggested solution
Declare the main language correctly. When the text is in Norwegian you should use nb (Bokmål) or nn (Nynorsk).
Priority (1-4)
Medium (3) 
WCAG relation
3.1.1 Language of page (level A)

**Comment by bjornreppen** [comment]
Bruk for eksempel Helmet? https://github.com/nfl/react-helmet

**Comment by helemork** [comment]
det er ikke litt overkill med et helt bibliotek for kun én tag?
men om vi skal endre mer metadata (som jeg synes vi bør pga seo) er det mer hensiktsmessig

**Comment by bjornreppen** [comment]
Ja, enig i at det er noe vi bør sjekke ut.. hvor mye kostnaden er.  For data.artsdatabanken.no var ikke dette et tema da det ble generert statiske web-sider.
