### ISSUE TITLE
Script for deployment av releases

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1509]
Pakker rulles nå automatisk ut i nin.test.artsdatabanken.no, men vi mangler verktøy for å rulle ut til produksjon.

**Comment by Myrdrahl** [comment]
Lagt til deployment-script for datagrunnlag og nin-innsyn for prod. Må trigges manuelt i "thehive", etter at det er godkjent i test-miljøet.
