### ISSUE TITLE
Administrativ grense: Fjern hardkodet ingress

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/nin-kart-frontend#1510]
Fjern midlertidig dumpet inn teskst:

"Norge er blant annet bygget opp av det vi kjenner som fastlandet med fylker og kommuner, som er en betydelig del av vårt territorialområde. Men Norge inneholder også flere øyer og øygrupper, og havområder som omtales som vår kontinentalsokkel."

**Comment by bjornreppen** [comment]
nei, har ikke fiksa det i klienten, bare kopiert teksten over i datasettet.

**Comment by helemork** [comment]
@svetlnaumova da har vi en ekstra jobb til deg :)
